### ISSUE TITLE
How to get the Login authentication working?

### ISSUE THREAD

**Issue by inlinemedia** [nuragic/marionette-bootstrap#1]
Great example app you build here, I'm currently diving into building my own marionette-backbone mobile applicatie. I was wondering if you can point me out how to get the login form really working?

I can see that the authentication function within the api folder has some demo credentials which are always fired. But I cant understand how to get the login form credentials into that function. 

Could you help me out maybe?

Thanks a lot!

**Comment by nuragic** [comment]
Hi! Thanks very much, I'm glad you're enjoying it.

The example app is using the HTTP Basic Authentication mechanism. So basically, in order to make it working in the real world you need to modify the authenticate() method in the API in order to check if the email exist and if the password for that user is correct and returns the result. I'll try to make this change in the code as soon as possible!

**Comment by nuragic** [comment]
Closing this issue because it doesn't apply in the current version.
